spring:
  datasource:
    url: jdbc:mysql://192.168.100.80:3306/app?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    host: 192.168.100.80
    port: 6379
    timeout: 1000
    lettuce:
      pool:
        min-idle: 5
        max-active: 8
xxl:
  job:
    admin:
      addresses: http://192.168.100.80:8888/xxl-job-admin
    accessToken:
    executor:
      address:
      ip:
      port: 9999
      appname: test-executor
      logpath: D:/Cache/Log
      logretentiondays: 7
app:
  swagger: true
  allow-list:
    - /auth/**
    - /v3/**
    - /swagger*/**
