spring:
  datasource:
    url: jdbc:mysql://192.168.221.80:3306/app?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: false
  redis:
    host: 192.168.221.80
    port: 6379
#自定义参数
app:
  test-param: test

#elastic-job
#scheduler:
#  config:
#    entrypoint: 192.168.3.10:30004
#    namespace: demoScheduler
