spring:
  datasource:
    url: jdbc:mysql://192.168.49.80:30002/app?characterEncoding=UTF-8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: false
  redis:
    host: 192.168.49.80
    port: 30001
xxl:
  job:
    admin:
      addresses: http://192.168.49.80:8888/xxl-job-admin
    accessToken:
    executor:
      address:
      ip:
      port: 9999
      appname: test-executor
      logpath: D:/log
      logretentiondays: 7
app:
  swagger: true
  allow-list:
    - /auth/**
    - /v3/**
    - /swagger*/**
flowable:
  db-history-used: true